### ISSUE TITLE
Right sidebar & notifications panel

### ISSUE THREAD

**Issue by awartoft** [interactive-solutions/backoffice-starterkit#4]

**Comment by fredrik-hjarner** [comment]
@macnibblet What should be found in the Right sidebar about similar stuff like W-löv: manage account, change password ?

With notifications panel I assume you mean something like this except maybe better looking:

![image](https://user-images.githubusercontent.com/35084243/35265136-8dd1925a-001f-11e8-939f-4d67ceb2d913.png)
